### ISSUE TITLE
SolidOS should create preferences file if missing

### ISSUE THREAD

**Issue by pheyvaer** [SolidOS/mashlib#79] opened 2019-11-14 07:28 UTC
When I open the profile (`https://ash.runi.ilabt.imec.be/profile/card#me`) of a user (after logging in) I only see the following:

![Screenshot from 2019-11-14 08-26-07](https://user-images.githubusercontent.com/9413528/68835621-c362c280-06b8-11ea-9ad7-0ab5ebaf5536.png)

In previous versions we were able to edit the profile details of the user here, no?
When checking the console I see that some data is missing and I get the same error when clicking the + button on the left.

`Error: Can't find a preferences file pointer in profile <https://ash.runi.ilabt.imec.be/profile/card>`

However, `https://ash.runi.ilabt.imec.be/profile/` works. I can see the Turtle file. So it might be more confusion on my part as what is expected to see at both locations. But when I try to save my changes I get the following error in the browser window 

`Error saving back: Error: Web error: 403 (User Unauthorized) on PUT of <https://ash.runi.ilabt.imec.be/profile/card>`

while the first error is also shown in the console.

**Comment by renyuneyun** [comment] 2022-02-10 12:53
I experience this issue too, but in a slightly different setting. I managed to get right of this issue on my setting.

I registered a "new pod name" for my new solid server (pod). Say the server address is `https://SERVER/`, and pod name is `foo`.

Therefore, when visiting `https://SERVER/`, it seem to show things. After logging in, clicking the "add" button, I got the error message as you do:
```
(via loadPrefs) Error: Can't find a preference file pointer in profile  <https://SERVER/foo/profile/card>
```

But, when visiting `https://SERVER/foo`, and do the same thing, I no longer encounter this error.

For me, `https://SERVER/` is the root directory (containing all users), and `https://SERVER/foo` is the pod that my new user actually resides. The permission issue may be the actual error.


But, same as you, my new user also doesn't have the `preference file pointer`. I looked at my account on a public solid server, and found this triple (which is missing from my own solid server):
```
@prefix space: <http://www.w3.org/ns/pim/space#>.
:me space:preferencesFile </settings/prefs.ttl>.
```

Maybe the root cause is incorrect initialization of new users? (But the error messages might worth be improving.)

**Comment by bourgeoa** [comment] 2022-02-11 08:29
@renyuneyun the original issue should have been closed.
you seem to run a CSS server where the pod name is <provider>/<username>.

> But, same as you, my new user also doesn't have the preference file pointer. I looked at my account on a public solid server, and found this triple (which is missing from my own solid server):

This is not a CSS error but a mashlib expectation. This should become a solid recommendation. There are on going discussions. See https://github.com/solid-profile

**Comment by jeff-zucker** [comment] 2022-02-11 16:17
Actually, the recommendation will be that SolidOS (or any app depending on a preferences files) should create the preferences file if it doesn't exist.  So, this is a needed feature in mashlib,

**Comment by renyuneyun** [comment] 2022-02-14 11:11
@bourgeoa Thanks for the info. When posting the comment, I did not recognize that there is a difference (in the way it works) between CSS and the public solid servers (e.g. solidcommunity.net) (SolidOS?). I thought CSS is just the core module of SolidOS.
Maybe more explanation on CSS and SolidOS page would be helpful to newcomers.

**Comment by bourgeoa** [comment] 2022-02-14 15:00
@renyuneyun You should report them to solidos.

**Comment by renyuneyun** [comment] 2022-02-14 17:17
Thank you very much!

**Comment by theRealImy** [comment] 2022-04-07 09:31
When moving to CSS this can be solved with "CSS supports this via a custom pod templates." ([see this comment](https://github.com/solid/solidcommunity.net/issues/62#issuecomment-1083615465)) and long-term SolidOS should create the file itself.

**Comment by timea-solid** [comment] 2022-11-23 08:30
Was done with: https://github.com/SolidOS/solid-logic/pull/39

**Closed by timea-solid** 2022-11-23 08:30 UTC
Labels: enhancement
